language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:

   # install some packages
   sudo apt-get update -qq
   sudo apt-get -y install libvirt-bin libvirt-dev libsys-virt-perl 
   sudo apt-get -y install libguestfs-tools guestfish

   # Prevent "Please tell me who you are" errors for certain DZIL configs
   - git config --global user.name "TravisCI"
   - git clone https://github.com/three18ti/Ceph-CLI.git ceph-cli

install:

   # Deal with all of the DZIL dependancies, quickly and quietly

   - cpanm --quiet --notest --skip-satisfied Dist::Zilla

   - cd ceph-cli && dzil authordeps --missing | xargs cpanm && dzil listdeps --missing | cpanm && dzil install && cd .. && rm -rf ceph-cli

   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied

   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

   - dzil listdeps | grep -vP '[^\w:]' | xargs cpanm --verbose --skip-satisfied


script:

   - dzil smoke --release --author

